name: Construire et Pusher l'image Docker

on:
  push:
    branches:
      - dev

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Récupérer le dépôt
      uses: actions/checkout@v4

    - name: Connexion à Docker Hub
      run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Construire et taguer l'image Docker
      run: |
        docker build -f Dockerfile.distroless -t ${{ secrets.DOCKER_USERNAME }}/demo-app:dev-${{ github.sha }} .

    - name: Pusher l'image Docker sur Docker Hub
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/demo-app:dev-${{ github.sha }}
