name: Cypress E2E Tests

on: [push]

jobs:
  cypress-tests:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_DB: django
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Django server in background
        run: |
          python manage.py migrate
          nohup python manage.py runserver 0.0.0.0:8000 &
        env:
          DATABASE_URL: postgres://user:password@localhost:5432/django

      - name: Wait for server to be ready
        run: |
          sleep 10
          curl --retry 10 --retry-delay 5 --retry-connrefused http://localhost:8000

      - name: Install Cypress
        run: npm install cypress --save-dev

      - name: Run Cypress tests
        run: npx cypress run
