name: Python Linter

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Installer Pylint
      run: pip install pylint

    - name: Linter Python
      run: pylint $(find . -name "*.py" ! -path "./.venv/*")
