name: Analyse de sécurité SAST

on: [push]

jobs:
  bandit:
    name: Analyse de sécurité avec Bandit
    runs-on: ubuntu-latest

    steps:
    - name: Récupérer le code
      uses: actions/checkout@v4

    - name: Configurer Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Installer Bandit
      run: pip install bandit

    - name: Scanner le code avec Bandit
      run: |
        bandit -r . -x unit_tests,integration_tests
