name: Générer une SBOM avec Syft

on:
  push:
    branches:
      - dev

jobs:
  generate-sbom:
    name: Génération de la SBOM
    runs-on: ubuntu-latest

    steps:
    - name: Récupérer le dépôt
      uses: actions/checkout@v4

    - name: Générer la SBOM avec Syft
      uses: anchore/sbom-action@v0.15.4
      with:
        source: dir:.
        format: syft-json
        output-file: sbom-syft.json

    - name: Enregistrer la SBOM comme artefact
      uses: actions/upload-artifact@v4
      with:
        name: sbom-syft
        path: sbom-syft.json
