name: Construction et Analyse de sécurité de l'image Docker

on: [push]

jobs:
  build:
    name: Construire et pusher l'image Docker
    runs-on: ubuntu-latest

    steps:
    - name: Récupérer le code source
      uses: actions/checkout@v4

    - name: Connexion à Docker Hub
      run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Construire et taguer l'image Docker
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/cicd-charlotte:dev-${{ github.sha }} .

    - name: Envoyer l'image Docker sur Docker Hub
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/cicd-charlotte:dev-${{ github.sha }}

  analyse-vulnerabilites:
    name: Analyse des vulnérabilités avec Trivy
    runs-on: ubuntu-latest
    needs: build
    continue-on-error: true  

    steps:
    - name: Installer Trivy
      run: |
        sudo apt-get update
        sudo apt-get install -y wget curl
        curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sudo sh -s -- -b /usr/local/bin

    - name: Connexion à Docker Hub
      run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Scanner l'image avec Trivy (seulement HIGH et CRITICAL)
      run: |
        trivy image --severity HIGH,CRITICAL ${{ secrets.DOCKER_USERNAME }}/cicd-charlotte:dev-${{ github.sha }}
