name: Scan ZAP Baseline

on: [push]

jobs:
  zap-scan:
    runs-on: ubuntu-latest
    continue-on-error: true

    steps:
      - name: Récupérer le dépôt
        uses: actions/checkout@v4

      - name: Lancer un scan ZAP Baseline
        uses: zaproxy/action-baseline@v0.10.0
        with:
          target: 'https://cicd-charlotte-deployment-321568021753.europe-west1.run.app'
          fail_action: false
          artifact_name: 'zap-report'
