name: Scan ZAP Baseline

on: [push]

jobs:
  zap-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Récupérer le dépôt
        uses: actions/checkout@v4

      - name: Lancer un scan ZAP Baseline
        uses: zaproxy/action-baseline@v0.10.0
        with:
          target: 'https://cicd-charlotte-deployment-321568021753.europe-west1.run.app'
          fail_action: false
          cmd_options: '-t 60'
          format: 'json'
          output_file: 'zap_report.json'

      - name: Télécharger le rapport ZAP en tant qu'artifact
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: zap_report.json
